### ISSUE TITLE
Building image with Docker fails

### ISSUE THREAD

**Issue by dbriasco** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#88] opened 2023-03-16 13:14 UTC
![image](https://user-images.githubusercontent.com/78444498/225625810-0d2e2ee1-bcfa-4809-836a-050c6ec1478f.png)

We try to build the image of the repository, but this error occurs on both Windows and Mac. All of these things using the dockerfile content in the repository.  
Seems to be an error on the download of some library with wget and gcc, especially this, "suite3270-3.6ga5-src"

**Comment by Gabriel-Repos** [comment] 2023-03-17 16:52
Hello, dbriasco and I, we were investigating and we found a possible solution to this error. Apparently it's a bug in the sources x3270 (3.6ga5) is resolved in (3.6ga9). Also, includes a --build=x86_64-unknown-linux-gnu parameter.

```
ARG BASE_IMAGE=3.7-alpine
FROM alpine as intermediate

RUN apk update && apk add wget gcc build-base libxt-dev libx11-dev xorg-server-dev libxmu-dev libxaw-dev bdftopcf ncurses-dev tcl tcl-dev mkfontdir && \
	wget http://x3270.bgp.nu/download/03.06/suite3270-3.6ga9-src.tgz && \ 
	tar xzvf suite3270-3.6ga9-src.tgz && \
	cd suite3270-3.6 && \
	./configure --build=x86_64-unknown-linux-gnu && \
	make x3270

FROM python:${BASE_IMAGE}

COPY --from=intermediate /suite3270-3.6/obj/x86_64-unknown-linux-gnu/x3270 /usr/lib/x3270

RUN apk update && apk add xvfb libxaw && rm -rf /var/cache/apk/* && \
    pip install robotframework six robotremoteserver && \
	mkdir /reports
RUN	ln -s /usr/lib/x3270/x3270 /usr/bin/x3270
ARG PYTHON_MAJOR
COPY source /usr/local/lib/python${PYTHON_MAJOR}.7/site-packages/Mainframe3270
COPY entrypoint.sh .
COPY tests /tests
WORKDIR reports

ENTRYPOINT ["/entrypoint.sh"]
```
This way the configure and make was done correctly..

**Comment by samuelpcabral** [comment] 2023-03-17 18:29
Great, you can send me a merge request.. or I can update in a few days.

**Comment by robinmatz** [comment] 2023-03-17 18:30
@dbriasco , @Gabriel-Repos , taking a look into the Dockerfile, I think there is a lot to simplify, and to change.

1. If we based the image on a debian distribution, like ubuntu:latest, we could just download x3270 and s3270 via apt-get, so jo need to build from source.

2. Currently, the Dockerfile copies the library content and is basically only designed to run this repositories tests. I think users might be more interested to run their own tests in a container. Therefore, why not just download the package from pypi?

Do you think adapting the image this way would help you with your use case?

**Comment by dbriasco** [comment] 2023-03-20 13:02
@robinmatz hi! the main idea was to run an image that works on Windows, and then, in other operative system. For the moment, is enough to build the image correctly

**Comment by dbriasco** [comment] 2023-03-21 15:42
Hi @robinmatz . I have tried the new version and build ok!

**Comment by robinmatz** [comment] 2023-03-25 14:40
Hi @dbriasco , I will leave this issue open for a while in case there will be issues running the container. If there is no further feedback it will be closed eventually.

**Comment by dbriasco** [comment] 2023-03-30 18:39
Hi @robinmatz @samuelpcabral , with @Gabriel-Repos were building the image, and it works, but when we try to execute the test case, it fails with the same error
![image](https://user-images.githubusercontent.com/78444498/228931916-a5fa8524-799e-413d-8625-eca074281cb0.png)

In the code, we comment all the "Take Screenshot" lines, but still appears that warning and message " BrokenPipeError: [Errno 32] Broken pipe". Could be a bug with Altran Library ?

This is the Dockerfile we are working : 
**_FROM ubuntu:22.04

# Setup the timezone to use, defaults to UTC
ENV TZ UTC-3
ARG DEBIAN_FRONTEND=noninteractive

#update the image
RUN apt-get update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa

#install python
RUN apt install -y python3.9
RUN apt install -y python3-pip

#install robot framework & libraries
COPY requeriments.txt /opt/robot-template/
RUN pip install -r /opt/robot-template/requeriments.txt
#RUN pip3 install --user --no-cache-dir robotframework-mainframe3270

# Define the default user who'll run the tests
ENV ROBOT_UID 1000
ENV ROBOT_GID 1000

# Set the reports directory environment variable
ENV ROBOT_REPORTS_DIR /opt/robot-template/Resultados

# Set the Resource directory environment variable
ENV ROBOT_RESOURCE_DIR /opt/robot-template/Recursos

# Set the working directory environment variable
ENV ROBOT_WORK_DIR /opt/robot-template/

# Set the tests directory environment variable
ENV ROBOT_TEST_DIR /opt/robot-template/Tests

# Set the tests directory file variable
ENV ROBOT_FILE_DIR /opt/robot-template/Recursos/Files/Entrada

COPY . /opt/robot-template

RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y --no-install-recommends \
	s3270 \
	xauth \
	python-tk \
	tk-dev \
	python3-tk \
	xvfb \
	wget \
	ca-certificates \
	x3270 \
	libnss3-dev libasound2 libxss1 libappindicator3-1 libindicator7 gconf-service libgconf-2-4 libgbm1 libpango1.0-0 xdg-utils fonts-liberation libcurl4 && \
	rm -rf /var/lib/apt/lists/*

#Robot Specific
# Create the default report, resources and work folders with the default user to avoid runtime issues
# These folders are writeable by anyone, to ensure the user can be changed on the command line.
RUN chown ${ROBOT_UID}:${ROBOT_GID} ${ROBOT_REPORTS_DIR} \
  && chown ${ROBOT_UID}:${ROBOT_GID} ${ROBOT_WORK_DIR} \
  && chown ${ROBOT_UID}:${ROBOT_GID} ${ROBOT_RESOURCE_DIR} \
  && chown ${ROBOT_UID}:${ROBOT_GID} ${ROBOT_TEST_DIR} \
  && chown ${ROBOT_UID}:${ROBOT_GID} ${ROBOT_FILE_DIR} \
  && chmod ugo+w ${ROBOT_REPORTS_DIR} ${ROBOT_WORK_DIR} ${ROBOT_RESOURCE_DIR} ${ROBOT_TEST_DIR} ${ROBOT_FILE_DIR}
  
# Allow any user to write logs
RUN chmod ugo+w /var/log \
  && chown ${ROBOT_UID}:${ROBOT_GID} /var/log
  
RUN chmod -R 777 /opt/robot-template

# Update system path
ENV PATH=/opt/robot-template/Docker/bin:$PATH

# Set up a volume for the generated reports
VOLUME ${ROBOT_REPORTS_DIR}

USER ${ROBOT_UID}:${ROBOT_GID}

# A dedicated work folder to allow for the creation of temporary files
WORKDIR ${ROBOT_WORK_DIR}

CMD ["/opt/robot-template/Docker/bin/run-tests-in-virtual-screen.sh"]_**

If you need further details, please tell us

**Comment by robinmatz** [comment] 2023-04-01 05:19
Hi @dbriasco , to reproduce the error, we also need the run-tests-in-virtual-screen.sh file as well as the command you are using to run the docker container.


From what you say in your last comment, it sounds like there is a problem with how xvfb is set up.

**Comment by dbriasco** [comment] 2023-04-03 14:47
Hi @robinmatz this is sh file:
#!/bin/sh

HOME=$ROBOT_WORK_DIR

robot -d $ROBOT_REPORTS_DIR $ROBOT_TEST_DIR $@

ROBOT_EXIT_CODE=$?

if [ $ROBOT_EXIT_CODE -ne 0 ] ; then
  echo "FINISH: There are test failures, failing build..."
  echo "Exiting with code 1."
  exit 1
else
  echo "FINISH: All tests passed!"
  echo "Exiting with code 0."
  exit 0
fi

To run docker, we are just using this:

docker run mainframe3270:latest

We could run now, but it seems there are a problem in a function with "Read All Screen" method

**Comment by dbriasco** [comment] 2023-04-03 16:09
Validar Tiempo de Espera
    #Tomamos los valores que nos otorga en pantalla, luego de ejecutar el job
    ${jobId}    Read    021    014    8  
    ${jobName}    Read    021    006    7
    #Tomamos un tiempo de espera  
    ${screen}	Read All Screen
    WHILE    $True
        IF    'ENDED AT N1' not in '''${screen}'''
            Sleep  3     
            Send Enter
        ELSE
            BREAK
        END 
        ${screen}	Read All Screen
    END 
    #Validamos que aparezcan los valores en la pantalla siguiente
    Page Should Contain String    ${jobId}
    Page Should Contain String    ${jobName}
    #Validamos que el código de retorno sea igual a 0000
    ${retorno}    Read    001    056    4
    Should Contain   ${retorno}    0000  
    Send Enter

**Comment by robinmatz** [comment] 2023-04-10 05:12
Two things I noticed. The reason why you run i to trouble with the visible=True option is because you didn't start the Xvfb. 

Containers are lightweight virtual machines that do not have a graphical user interface (GUI). However, x3270 is an application that needs a GUI. Therefore, the typical approach to run GUI applications in a container is to use a virtual screen like Xvfb.

In short, you can run your robot tests with this command prepended:
```xvfb-run --auto-servernum <your robot command>```

Second, I saw that you prepended a 0 to the ypos and xpos arguments in your read commands. Maybe you can try without these?

**Comment by robinmatz** [comment] 2023-04-10 05:23
It seems that prepending zeros does not cause the issue. It might be an encoding issue.

Is the Page Should Contain  ${jobId} causing the issue?

**Comment by dbriasco** [comment] 2023-04-11 15:51
> Two things I noticed. The reason why you run i to trouble with the visible=True option is because you didn't start the Xvfb.
> 
> Containers are lightweight virtual machines that do not have a graphical user interface (GUI). However, x3270 is an application that needs a GUI. Therefore, the typical approach to run GUI applications in a container is to use a virtual screen like Xvfb.
> 
> In short, you can run your robot tests with this command prepended: `xvfb-run --auto-servernum <your robot command>`
> 
> Second, I saw that you prepended a 0 to the ypos and xpos arguments in your read commands. Maybe you can try without these?

About these, prepending zeros does not cause the issue. But with the command of xvfb and visible=True, appears to be Ok! The only thing i have to change is the position i'm validating, this line:
${retorno} Read 001 056 4  works with the position 066 instead of 056

Thanks a lot for your help!

**Comment by dbriasco** [comment] 2023-06-12 20:13
Hi @samuelpcabral, sorry for the late answer, yes, close it

**Closed** 2023-06-13 09:20 UTC
Labels: bug, help wanted
