### ISSUE TITLE
Connect AS400 with SSL Certificate

### ISSUE THREAD

**Issue by FWDQK** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#74] opened 2023-01-20 10:44 UTC
Hi Team,
We are facing issues in connecting to AS400 host on port 992 .cer with certificate file.
We have tried below code snippet, still we are not able to connect.

${extra_args}           Create List     --accepthostname     myhost.com     --cafile     ${CURDIR}/cafile.crt
Open Connection    Hostname    port=992      extra_args=${extra_args}

If you can give any suggestions on it, it will be vert helpful.

**Comment by robinmatz** [comment] 2023-02-12 19:51
Hi @FWDQK ,

sorry for the late reply. Can you please provide an error message?
Please note that x3270 command line options only use one hyphen (use "-cafile" instead of "--cafile").

**Comment by FWDQK** [comment] 2023-02-13 04:43
Hi @robinmatz ,

I have tried connect with -cafile/-cadir still not able to connect it.
I have .cer certificate file.

Error I get :
[WinError 10061] No connection could be made because the target machine actively refused it.

**Comment by robinmatz** [comment] 2023-02-13 04:59
Ok. I do not know your requirements. But if you are trying to make a connection using a certificate to authenticate against the host, the option you want is "-certfile". 

Using this, you should remove the "-cafile" option.

**Comment by FWDQK** [comment] 2023-02-13 05:18
Hi @robinmatz ,
Here is my requirement : I want to connect AS400 server with SSL certificate on port 992, I have .cer certificate file of the server.

I tried -certfile also but did not succeed.
Can you please suggest any solution on this.

**Comment by robinmatz** [comment] 2023-02-13 11:04
Is the error message still the same?

**Comment by robinmatz** [comment] 2023-02-13 11:04
Ok. I do not know your requirements. But if you are trying to make a connection using a certificate to authenticate against the host, the option you want is "-certfile". 

Using this, you should remove the "-

**Comment by FWDQK** [comment] 2023-02-13 11:06
> Is the error message still the same?

Yes

**Comment by robinmatz** [comment] 2023-02-13 11:09
According to the x3270 -certfile only supports pem or asn1 files.

You can try to change the file extension of your cert file from .cer to .pem given its content is plain text.

**Comment by FWDQK** [comment] 2023-02-14 04:23
Hi @robinmatz ,

I have tried with .pem certificate file also still I am getting the below error.
[WinError 10061] No connection could be made because the target machine actively refused it

**Comment by robinmatz** [comment] 2023-02-14 11:09
They error message you are getting indicates that there is a networking issue. That could be that 
- there is no process listening on port 992 on the target machine
- there is a firewall that is blocking network traffic from your PC to the target host

In any case, you should try and contact your server admin and ask for their help. Usually, they have access to system logs that help give more information on what's going on.



The last thing we can do for you is take a look the x3270 trace file.

For this, you have to rerun your test with the -tracefile option. Before you send the file, please make sure it does not contain any sensitive information like IP addresses, username, passwords, etc.

**Comment by FWDQK** [comment] 2023-02-14 13:28
I tried to generate trace, but not able ot generate it with certfile option.
I have tried -noverifycert and -clientcert options. Please refer attached trace for it.
[traces.zip](https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/files/10732793/traces.zip)

**Comment by robinmatz** [comment] 2023-02-14 18:39
Ok, so from the traces I gather that you successfully made contact with the host, and that there is indeed a process listening on port 992.

I found this line in the version with `-clientcert`:
> 20230214.201336.449 error: TLS: CertFindCertificateInStore: error 0x80092004 (Cannot find object or property.)

What's curious is that with `wc3270` the `-clientcert` option does not take a path, but the name of the certificate in your PC's certificate store.

This means that you have to import the .cer certificate file into your certificate store. Then, you pass the name of the imported certificate to the `-clientcert` parameter.

**Comment by FWDQK** [comment] 2023-02-15 04:38
I have pass Certificate name from certificate store Friendly Name section, still I am getting the same error.
![Capture](https://user-images.githubusercontent.com/111964982/218932148-3fed2dcf-3a0c-4c91-99ee-59f4e3f82f4c.PNG)

**Comment by robinmatz** [comment] 2023-02-16 11:19
Have you made sure, the certificate is placed inside your *personal* certificate store?

**Comment by FWDQK** [comment] 2023-02-16 12:15
yes, certificate is there in Personal Certificate Store

**Comment by robinmatz** [comment] 2023-02-16 16:23
I was not able to reproduce the behavior you described, e.g. in my case the client certificate was accessed successfully from the personal certificate store.


Since this issue is specific to the x3270 project, I suggest you raise an issue in their GitHub repository: https://github.com/pmattes/x3270

**Comment by robinmatz** [comment] 2023-02-21 19:41
Closing this issue now, because an issue has been raised in the x3270 project.

**Closed** 2023-02-21 19:41 UTC
