### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by FWDQK** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#120] opened 2023-11-26 11:20 UTC
Hi Team,
Each time we run as Open connection,  wc3270 window launches and gets closed immediately. 
Wait field detected keyword fails with an error: ConnectionResetError: [winerror 10054] an existing connection was forcibly closed by the remote host.

Please help to suggest solution for this, as manually we are able to open the wc3270 window and close it properly.

**Comment by FWDQK** [comment] 2023-11-28 17:26
Hi Team 
Any update on this issue?

**Comment by samuelpcabral** [comment] 2023-11-29 14:31
Hi @FWDQK what version of the library you are using? I just run the tests of version 4.0 and everything is working as expected.

Do you have more informations?

**Comment by FWDQK** [comment] 2023-11-29 15:11
> Hi @FWDQK what version of the library you are using? I just run the tests of version 4.0 and everything is working as expected.
> 
> Do you have more informations?

Hi, We are also same version 4.0
But we are facing this issue much frequently in current environment. 
For other environment, it is working fine.

**Comment by robinmatz** [comment] 2023-12-03 04:50
Hi @FWDQK ,
the error message, [winerror 10054] an existing connection was forcibly closed by the remote host., basically says that the host that you are tryring to connect to closed the connection made by wc3270.

There might be multiple reasons as to why this happens. One of them might be that you host only allows for one connection at a time, so that when you connect to it with multiple wc3270 clients, it shuts down some of them.

In any case, this is not really possible for us to debug, since the issue is most likely rooted in you environment setup. If you haven't already, please also get in contact with your system administrators, as they may have additional information as to why the host shuts down the connections from your client.

**Closed** 2024-01-11 09:26 UTC
